#!/bin/sh

# __author__ = "Jose Antonio Navas Molina"
# __copyright__ = "Copyright 2013, The QIIME-scaling project"
# __credits__ = ["Jose Antonio Navas Molina"]
# __license__ = "BSD"
# __version__ = "0.0.2-dev"
# __maintainer__ = "Jose Antonio Navas Molina"
# __email__ = "josenavasmolinao@gmail.com"

exec pyqi --driver-name scaling --command-config-module scaling.interfaces.optparse.config -- "$@"